run:
  tests: false


linters:
  enable-all: false
  disable-all: true
  enable:
   - govet
   - golint
   - gofmt
   - deadcode
   - goimports
   - misspell
   - ineffassign
   - staticcheck
   - varcheck
   - structcheck
   - maligned
   - vetshadow
   - goconst
   - interfacer

issues:
  exclude-rules:
   # See https://github.com/golangci/golangci-lint/issues/741
   - path: pgp/openpgp.go
     linters:
      - staticcheck
     text: SA1019
